[project]
name = 'Blockchain-Based-Shared-Childcare-Coordination'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.contribution-tracking]
path = 'contracts/contribution-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.family-registration]
path = 'contracts/family-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.skill-verification]
path = 'contracts/skill-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
